# Generated by Django 6.0.2 on 2026-02-13 16:22

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_remove_user_is_student_remove_user_is_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
