# Generated by Django 6.0.2 on 2026-02-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_role_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="Цифра класса"),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
                "ordering": ["number"],
            },
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="grade",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="school_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="users.schoolclass",
                verbose_name="Класс",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="school_classes",
            field=models.ManyToManyField(
                related_name="teachers", to="users.schoolclass", verbose_name="Классы"
            ),
        ),
    ]
