# Generated by Django 6.0.2 on 2026-02-14 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0005_remove_studentprofile_parent_phone_user_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userphonenumber",
            options={
                "verbose_name": "Номер телефона",
                "verbose_name_plural": "Номера телефонов",
            },
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="subjects",
            field=models.ManyToManyField(
                related_name="students",
                to="courses.subject",
                verbose_name="Изучаемые предметы",
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="subjects",
            field=models.ManyToManyField(
                related_name="teachers",
                to="courses.subject",
                verbose_name="Предметы обучения",
            ),
        ),
        migrations.AlterField(
            model_name="userphonenumber",
            name="number",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+375-XX-XXX-XX-XX'.",
                        regex="^\\+375-\\d{2}-\\d{3}-\\d{2}-\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="userphonenumber",
            constraint=models.UniqueConstraint(
                fields=("user", "number"), name="unique_user_phone"
            ),
        ),
    ]
