# Generated by Django 6.0.2 on 2026-02-14 18:37

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userphonenumber_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
