# Generated by Django 6.0.2 on 2026-02-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_studentprofile_user_alter_teacherprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_students",
                to="users.teacherprofile",
                verbose_name="Закрепленный учитель",
            ),
        ),
    ]
