# Generated by Django 6.0.2 on 2026-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_studentprofile_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="teacher",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="my_students",
                to="users.teacherprofile",
                verbose_name="Учителя",
            ),
        ),
    ]
