# Generated by Django 6.0.2 on 2026-03-12 19:10

import django.contrib.auth.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_studentprofile_teacher_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="role",
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="schoolclass",
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="studentprofile",
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="teacherprofile",
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="userphonenumber",
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
