# Generated by Django 6.0.2 on 2026-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_role_managers_alter_schoolclass_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/%Y/%m/", verbose_name="Аватар"
            ),
        ),
    ]
