# Generated by Django 6.0.2 on 2026-09-01 18:02

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.functions.datetime
import users.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0026_alter_topic_options"),
        ("users", "0013_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="Список дней недели (0=Пн, 1=Вт, ..., 6=Вс)",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость занятия",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата первого урока")),
                ("end_date", models.DateField(verbose_name="Дата окончания серии")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_rules",
                        to="users.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_rules",
                        to="users.teacherprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(verbose_name="Дата занятия")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Длительность (мин)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Назначено"),
                            ("COMPLETED", "Проведено"),
                            ("CANCELED", "Отменено"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Статус занятия",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("UNPAID", "Не оплачено"), ("PAID", "Оплачено")],
                        default="UNPAID",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Стоимость (руб)",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Тема урока"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Причина отмены"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="users.studentprofile",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="users.teacherprofile",
                        verbose_name="Преподаватель",
                    ),
                ),
                (
                    "recurring_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="schedule.recurringrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "date"],
                        name="schedule_le_teacher_6c9a6c_idx",
                    ),
                    models.Index(
                        fields=["student", "date"],
                        name="schedule_le_student_126fde_idx",
                    ),
                ],
            },
            managers=[
                ("objects", users.models.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
