# Generated by Django 6.0.2 on 2026-02-19 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_section_topic"),
        ("users", "0009_alter_studentprofile_user_alter_teacherprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topics",
                to="users.schoolclass",
            ),
        ),
    ]
