# Generated by Django 6.0.2 on 2026-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_topic_content_type_topic_text_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("theory_and_practice", "Теория и практика"),
                    ("simulator", "Тренажер"),
                ],
                default="theory",
                max_length=20,
            ),
        ),
    ]
