# Generated by Django 6.0.2 on 2026-02-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_homework_delete_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="config",
        ),
        migrations.RemoveField(
            model_name="homework",
            name="description",
        ),
        migrations.RemoveField(
            model_name="homework",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="homework",
            name="score",
        ),
        migrations.AddField(
            model_name="homework",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Содержание (текст)"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homework",
            name="simulator_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.simulatorconfig",
                verbose_name="Конфигурация тренажера",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Срок сдачи"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="hw_type",
            field=models.CharField(
                choices=[
                    ("theory", "Теория"),
                    ("practice", "Практика"),
                    ("simulator", "Тренажер"),
                ],
                max_length=20,
                verbose_name="Тип задания",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
