# Generated by Django 6.0.2 on 2026-02-27 15:40

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_remove_homework_config_remove_homework_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="homeworks/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="courses.homework",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
