# Generated by Django 6.0.2 on 2026-02-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_homeworkfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homework",
            options={"ordering": ["-created_at"]},
        ),
    ]
