# Generated by Django 6.0.2 on 2026-02-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_homework_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.topic",
                verbose_name="Тема",
            ),
        ),
    ]
