# Generated by Django 6.0.2 on 2026-02-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_homework_subject_homework_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.section",
                verbose_name="Раздел",
            ),
        ),
    ]
