# Generated by Django 6.0.2 on 2026-03-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_homework_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="is_active",
        ),
        migrations.AddField(
            model_name="homework",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
