# Generated by Django 6.0.2 on 2026-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_remove_homework_is_active_homework_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
