# Generated by Django 6.0.2 on 2026-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_homework_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="content_type",
        ),
        migrations.AddField(
            model_name="simulatorconfig",
            name="config_type",
            field=models.CharField(
                choices=[
                    ("practice", "Тренажер (случайные задания)"),
                    ("exam", "Самостоятельная работа (фиксированные задания)"),
                ],
                default="practice",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="text_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Теория (Markdown/HTML)"
            ),
        ),
    ]
