# Generated by Django 6.0.2 on 2026-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_remove_topic_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="include_site_theory",
            field=models.BooleanField(
                default=False, verbose_name="Включить теорию с сайта"
            ),
        ),
    ]
