# Generated by Django 6.0.2 on 2026-03-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_homework_include_site_theory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order", "title"]},
        ),
        migrations.AddField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Порядок вывода (чем меньше число, тем выше)"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsections",
                to="courses.section",
            ),
        ),
    ]
