# Generated by Django 6.0.2 on 2026-03-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_alter_section_options_section_order_section_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
