# Generated by Django 6.0.2 on 2026-03-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_alter_section_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок тем внутри раздела"
            ),
        ),
    ]
