# Generated by Django 6.0.2 on 2026-03-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_topic_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
