# Generated by Django 6.0.2 on 2026-03-08 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_alter_topic_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homework",
            options={},
        ),
        migrations.AddField(
            model_name="homework",
            name="actual_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Полученный балл"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="is_theory_read",
            field=models.BooleanField(default=False, verbose_name="Теория изучена"),
        ),
        migrations.CreateModel(
            name="HomeworkResponseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="responses/%Y/%m/%d/", verbose_name="Фото решения"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="courses.homework",
                    ),
                ),
            ],
        ),
    ]
