# Generated by Django 6.0.2 on 2026-03-08 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_alter_homework_options_homework_actual_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="actual_score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Полученный балл",
            ),
        ),
    ]
