# Generated by Django 6.0.2 on 2026-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_alter_homework_actual_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ждет решения"),
                    ("review", "На проверке"),
                    ("completed", "Выполнено"),
                    ("correction", "На доработке"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="teacher_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий учителя"
            ),
        ),
    ]
