# Generated by Django 6.0.2 on 2026-03-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0025_alter_homework_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["order", "title"]},
        ),
    ]
